apiVersion: v1
kind: Service
metadata:
  name: github-eventsource-service
  namespace: argo
spec:
  selector:
    app: argo-events
    eventsource-name: github-eventsource
  ports:
  - port: 12000
    targetPort: 12000
    name: webhook