apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github
  namespace: argo-events
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: github-dep
      eventSourceName: github
      eventName: github_el
  triggers:
    - template:
        name: github-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: build-and-push-
                namespace: argo
              spec:
                entrypoint: build
                templates:
                  - name: build
                    container:
                      image: gcr.io/kaniko-project/executor:latest
                      args:
                        - "--context=git://github.com/Adanrleon/Argocd.git"
                        - "--dockerfile=Dockerfile"
                        - "--destination=host.docker.internal:5001/mi-app:v1.0.0"
                        - "--insecure"