apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gitops
spec:
  replicas: 1 # Solo queremos 1 copia de nuestra app corriendo por ahora
  selector:
    matchLabels:
      app: app-gitops
  template:
    metadata:
      labels:
        app: app-gitops
    spec:
      containers:
      - name: web
        # Tras el primer Workflow, esta etiqueta será el SHA exacto del commit.
        # No usamos :latest porque Kubernetes no reinicia Pods al cambiarla.
        image: adanleon/app-gitops:10df19220f72dfaa4ede2e7d100e907cc60c4c1d
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80 # Nginx expone el puerto 80 dentro del contenedor
